// SEE EARTH V1 · Phase 2 · alpha-api
// -----------------------------------
// This file is auto-generated by Next.js on first build.
// Do not edit it manually.
// Reference: https://nextjs.org/docs/app/api-reference/config/typescript

/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited
// see https://nextjs.org/docs/app/api-reference/config/typescript for more information.